spring:
  profiles:
    active: mysql_local
  main:
    allow-bean-definition-overriding: true
server:
  port: 8089

---
spring:
  profiles: mysql_local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/transactions_database
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

---
spring:
  profiles: mysql_docker
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://transaction-tracker-database-mysql:3306/transactions_database
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

---
spring:
  profiles: h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./src/main/resources/h2/db
    username: root
    password: password

---
spring:
  profiles: mongo
  data:
    mongodb:
      uri: mongodb://localhost:27017/transactions_database